[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Résumé"
  url = "resume/"
  weight = -109

[[main]]
  name = "About"
  url = "about/"
  weight = -108

#Submenus are done this way: parent -> identifier
[[main]]
  name = "Interview Preparation"
  identifier = "InterviewPrep"
  weight = -107
[[main]]
 parent = "InterviewPrep"
 name = "Data Structures And Algorithms"
 url = "dsa/"

[[main]]
 name = "Papershelf"
 url = "papershelf/"



# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/codidharma"
[[social]]
  name = "X"
  weight = 2
  url = "https://x.com/codidharma"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/mandar-dharmadhikari"
[[social]]
  name = "rss"
  weight = 5
  url = "index.xml"

[[social]]
  name = "youtube"
  url = "https://www.youtube.com/@codidharma"
  weight= 4
# other supported social links
 
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"